services:
  test-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    container_name: test-app
    working_dir: /src
    volumes:
      - .:/src

  postgres:
    image: postgres
    container_name: postgres-alpine
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: services
    ports:
      - "5433:5432"
