services:
  test-app:
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file:
      - .env
    ports:
      - "3000:3000"
    container_name: test-app
    working_dir: /src
    volumes:
      - .:/src
      - /src/dist
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres
    container_name: postgres-alpine
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
      POSTGRES_DB: services
    ports:
      - "5433:5432"

  redis:
    image: redis:alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: redis-server --databases 2
    volumes:
      - redis_data:/data

volumes:
  redis_data: