export const PAY_NET_CONNECT_SOURCE = 'PAY_NET_CONNECT_SOURCE';
export const MODELS = {
  AUTH: 'AUTH_MODEL',
  USERS: 'USERS_MODEL',
  OTP: 'OTP_MODEL',
  BASKET: 'BASKET_MODEL',
  ORDER: 'ORDER_MODEL',
  PRODUCT: 'PRODUCT_MODEL',
  CATEGORY: 'CATEGORY_MODEL',
};
